### ISSUE TITLE
cardano-byron-proxy infinitely updating sqlite index

### ISSUE THREAD

**Issue by cleverca22** [input-output-hk/cardano-byron-proxy#9]
ive noticed that byron-proxy pegs my cpu at 100% and `strace` reveals its infinitely updating the sqlite database, which is then infinitely spamming `sync()` calls to my disk

cause not yet obvious

**Comment by cleverca22** [comment]
```
  191 sqliteRollforward epochSlots conn hdr = do
- 192     putStrLn $ show $ sformat ("rolling forward ("%int%","%int%") from "%string) epoch slot (prettyCallStack callStack)
```
from the extra logs this prints out, it appears to be rebuilding the sqlite index, by re-inserting every single block in the chain
its using a `ON CONFLICT DO NOTHING` so that explains why the diff on the db reveals no actual changes
but its still doing a full creation of the sqlite journal, and flushing the disk, for every single block

it would be better for performance to do it all in a sqlite transaction

and i need to look into why its rebuilding the db on every single run of the proxy

**Comment by cleverca22** [comment]
one minor nitpick, is that i notice its not using prepared statements
https://hackage.haskell.org/package/sqlite-simple-0.4.16.0/docs/Database-SQLite-Simple.html#g:17
thats not likely related to the main performance problem or the bug, but it would be a nice improvement to performance

it looks like its just a matter of calling either `openStatement`+`closeStatement` or using `withStatement` when you open the database, and storing the `Statement` for each query in a data record

then to insert rows, you would use something like
```haskell
bind stmt (hashBytes, epoch, slot)
Nothing <- nextRow stmt
reset stmt
```
ideally, the `reset` would be under a `finally`, or things will break next time the statement is used

**Comment by avieth** [comment]
Are you using tip of `avieth/chaindb`? I did some fixes on Friday w.r.t. the index.

Yes, it'd be best to do it all in one transaction, _assuming_ we have a batch of work to do up-front. But the way it works is the index follows the `ChainDB` by way of a `ChainDB.Reader`, getting one roll forward/backward each time. Currently the `synchronous` pragma is set to 0 to give a speedup (TBD whether this will cause any unacceptable consistency problems, but I don't think it will). 

How long did you let the program go? Eventually, if the `ChainDB` stops updating, the index will catch up. If you have a miannet sync, for example, then you have about 3 million entries to put into the index, which takes time of course. Strange that it's spamming `sync()`, since `synchronous = 0`.

**Comment by cleverca22** [comment]
i left it running for a few hours, logging every roll forward, and it stopped somewhere in epoch 16 with no errors

i wiped the chain state, started it again, and it stopped in epoch 16 again, this time with an error

```
rolling forward (16,19337)
rolling forward (16,19338)
[iohk.byron-proxy.db:Error:ThreadId 1646] [2019-08-04 17:39:03.88 UTC] InvalidBlock {_validationErr = ExtValidationErrorLedger (ChainValidationUTxOValidationError (UTxOValidationTxValidationError (TxValidationTxTooLarge 14622 4096))), _invalidPoint = Point {getPoint = At (Block {blockPointSlot = SlotNo {unSlotNo = 364939}, blockPointHash = AbstractHash 5af5556ef4e2491c9637718646742088f27c380e4cf4290ed40d3f6ee0fd404a})}}
[iohk.byron-proxy.diffusion:Debug:ThreadId 1646] [2019-08-04 17:39:04.74 UTC] Read block d0d46f61 difficulty 365040
[iohk.byron-proxy.diffusion:Debug:ThreadId 1646] [2019-08-04 17:39:12.90 UTC] Read block 24d34f81 difficulty 365296
```

**Comment by avieth** [comment]
This is unrelated o the index.
